brew install atk
brew install hicolor-icon-theme
brew install openssl
brew install atkmm
brew install highlight
brew install pandoc
brew install autoconf
brew install hub
brew install pandoc-citeproc
brew install automake
brew install icu4c
brew install pango
brew install awscli
brew install ilmbase
brew install pangomm
brew install bdw-gc
brew install imagemagick
brew install parallel
brew install boost
brew install inkscape
brew install pcre
brew install cairo
brew install isl
brew install pdflib-lite
brew install cairomm
brew install isl011
brew install pillow
brew install cask
brew install jhead
brew install pixman
brew install cloc
brew install jpeg
brew install pkg-config
brew install cloog
brew install jq
brew install popt
brew install cloog018
brew install json-c
brew install postgresql
brew install cmake
brew install lame
brew install proj
brew install coreutils
brew install leptonica
brew install py2cairo
brew install cuty_capt
brew install libass
brew install pygobject
brew install dopewars
brew install libbs2b
brew install pygtk
brew install dos2unix
brew install libepoxy
brew install pyqt5
brew install eigen
brew install libffi
brew install python
brew install emacs
brew install libgeotiff
brew install python3
brew install emscripten
brew install libgpg-error
brew install qt
brew install fdk-aac
brew install libksba
brew install qt5
brew install ffmpeg
brew install liblwgeom
brew install rcm
brew install ffms2
brew install libmpc
brew install readline
brew install fftw
brew install libmpc08
brew install reaver
brew install flac
brew install libogg
brew install rename
brew install fontconfig
brew install libpng
brew install rtmpdump
brew install freetype
brew install libsamplerate
brew install rubberband
brew install freexl
brew install libsigc++
brew install sbt
brew install fribidi
brew install libsndfile
brew install scala
brew install gcc
brew install libspatialite
brew install sip
brew install gcc48
brew install libtiff
brew install spoof-mac
brew install gd
brew install libtool
brew install sqlite
brew install gdal
brew install libvorbis
brew install subliminal
brew install gdbm
brew install libxml2
brew install tesseract
brew install gdk-pixbuf
brew install libyaml
brew install texi2html
brew install geos
brew install little-cms
brew install thefuck
brew install gettext
brew install little-cms2
brew install theora
brew install giflib
brew install llvm
brew install valgrind
brew install git
brew install lua
brew install vapoursynth
brew install git-lfs
brew install lzlib
brew install webp
brew install glib
brew install matplotlib
brew install wget
brew install glibmm
brew install matplotlib-basemap
brew install wxmac
brew install gmp
brew install maven
brew install x264
brew install gmp4
brew install mongodb
brew install x265
brew install gnuplot
brew install mpfr
brew install xmlstarlet
brew install gobject-introspection
brew install mpfr2
brew install xvid
brew install graphicsmagick
brew install mpv
brew install xz
brew install graphviz
brew install multimarkdown
brew install yasm
brew install gsettings-desktop-schemas
brew install mvtools
brew install youtube-dl
brew install gsl
brew install node
brew install yuicompressor
brew install gtk+
brew install numpy
brew install zeromq
brew install gtk+3
brew install oniguruma
brew install zimg
brew install gtkmm
brew install opencv
brew install harfbuzz
brew install openexr
